spring:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 1000MB
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/dev-db